### ISSUE TITLE
Versioning schemas

### ISSUE THREAD

**Issue by jo-basevi** [ACCESS-NRI/schema#4]
As we may be adding schemas for checksums and performance metrics to this repository, it would be good to have standard way to handle different schemas versions. Some options are:

1. **Schemas per branch and specific schema git tags.** So a repository organisation similar to Cosima's [ACCESS-OM3 configurations](https://github.com/COSIMA/MOM6-CICE6). For example, for the existing schema `experiment_asset.json`, there's a branch name called `experiment_asset` and related tag versions of `experiment_asset-v1.0.0`. Descriptions of schema would need to be in the README of the `main` branch for discoverability. This will have the benefit of separate git histories. 
2. **Just specific schema git tags.** For example, a tag could be `experiment_asset-v1.0.0` but have all the files in the `main` branch. +: Schema visibility, git history for 1 file. -: Shared git history, long tags.
3. **Creating separate files per schema version.**. For example, `experiment-asset-v1.0.json` or directory structure of:
```
─ experiment-asset
│     v1.0.json
│     v1.1.json
─ schema2 
```
+: Schema and version visibility. -: Need to guarantee that earlier versions of schema do not change,  no git history of 1 file.
4. **Creating a separate repositories per schema.** +: Simple tags and separate git histories. -: no central location (would git submodules work here?)

Thanks to @dougiesquire and @aidanheerdegen for the ideas! I have a slight preference for option 1 but I think any option would work fine.

**Comment by aidanheerdegen** [comment]
I don't think the use case for schema matches the ACCESS-OM3 model configurations. For each configuration the contents of the repo (branch) is completely different. For the schema all branches can contain all schema, separated into subdirectories if necessary. Because both need long tags with schema versions embedded 1 & 2 effectively collapse into the same option IMO.

Option 3 is close to what was recommended in this discussion

https://github.com/json-schema-org/website/issues/197

specifically: https://github.com/json-schema-org/website/issues/197#issuecomment-1829648043

> Having said that, or recommendation is that schemas should be immutable and if a new version is required, we recommend use a new file with new ID, leaving the decision of how to manage it up to the users.

Which would be a modification of option 3 if sub-directories were used:
```
─ experiment-asset
│    experiment-asset-v1.0.json
│    experiment-asset-v1.1.json
─ schema2 
```
Where each schema is uniquely named and immutable. Would probably still require long `git` tags encoding the schema name.

Option 4 sounds technically appealing, on the surface, but socially problematic, and also maintenance/upkeep could be an issue. `git submodules` is an option, but I have grown to dislike them. Separate repos do have the positive of keeping issues and discussions localised to the specific schema, but this could just as easily be seen as a downside.

**Comment by dougiesquire** [comment]
I really don't have strong opinions about this, though I agree that having versioning is important.

My original reaction to options 3 is that it sounds like the worst of all worlds:
- schema-specific git tags are required anyway to make the schema versions "immutable"
- the tags make the version info in the filename somewhat redundant
- there's the possibility for the tag and filename versions to get out of sync

But my use of these schema up to now has always been directly through GitHub, requesting a specific commit/tag. If there are use cases where the git info of a particular schema is lost or hard to find, then it's important to have the version encoded in the file somewhere (e.g. in the filename as suggested).

**Comment by CodeGat** [comment]
Just putting my hat into the ring, I think I like option 1 the best. 

Option 1: It also has analogues to what we are doing in `access-nri/access-om2-configs` with our special config branches, although it'd be much, much more lightweight (I suppose the branch would only contain that file?).

Option 2: I don't like the idea of having all of the schemas in the same branch. Could get unwieldy. Somewhat harder to articulate, but I also don't like the idea of going to an earlier `git tag` for an earlier version of `schema X`, and having a bunch of different, unrelated schemas at different points in their histories in the repo, too. But that might just be my preference. 

Option 3: Could work I suppose...but still don't like storing all the schema in the same branch, personally. 

Option 4: If we start supporting a lot of schema, I'd much rather have a branch explosion where we can put in the `main` `README.md` where things are, than a repository explosion with no central place to find them. Unlike @aidanheerdegen, I love `git submodules`, but don't think they'd be a good fit here, either.

**Comment by aidanheerdegen** [comment]
The big downside of using branches (option 1) is that GitHub does not index them, which makes discovery difficult.

It seems that schema are often stored in databases themselves, and exposed through a schema registry

https://wundergraph.com/blog/a-open-source-schema-registry
https://github.com/snowplow/iglu

Maybe schema have tended to evolve dynamically, so there are tools to capture the current state rather than enforce versioning etc in the design phase? c.f.

https://www.schemacrawler.com

**Comment by harshula** [comment]
Which of these options will allow a person to easily grep/search for a string across all schemas?

**Comment by dougiesquire** [comment]
> Which of these options will allow a person to easily grep/search for a string across all schemas?
Across the latest version of all schemas: 2
Across all versions of all schemas: 3

**Comment by harshula** [comment]
Hypothetically, a user may want to search all versions of a particular schema to find out when a particular element was introduced.

**Comment by jo-basevi** [comment]
Ok, thats is a good point. So to go with option 3 - having a separate file per schema version. I think it would be worth have a brief change log file associated with each schema, with changes to schema for each version. Then if there's more schemas, or more producers/consumers of records using schemas, we could look into setting up a schema registry to store/access schemas and their versions.

**Comment by aidanheerdegen** [comment]
A `CHANGELOG` per schema sounds like a good idea. In which case utilising a directory structure might be worthwhile to allow for a single `CHANGELOG` file per schema. Otherwise we'd end up with `CHANGELOG.schema_name` or similar, potentially making it messier and harder to navigate.

Other opinions are welcome though!

**Comment by aidanheerdegen** [comment]
Downsides of sub-directories:

1. Might require reorganisation of existing repo/schema, breaking existing tools (bad!)
2. How to organise sub-directories? Do we go for a deeper nesting scheme? All catalogs eventually hit limitations, so keep as flat as possible?

**Comment by CodeGat** [comment]
Would this issue be considered closed now?

**Comment by dougiesquire** [comment]
It looks like you've chosen a way forward, but it's not clear to an outsider how to organise subdirectories. Should all schemas live in `au.org.access-nri`? What does the next level (your `model`) describe?

I'd like to update the `experiment_asset.json` and `file_asset.json` schemas, but it's not clear to me how to slot in to what you've added.

**Comment by aidanheerdegen** [comment]
> Should all schemas live in `au.org.access-nri`?

If we own them, yes. This gives us the flexibility to host schema from other sources, and allows others to make copies of our schema and still retain information about their original provenance.

I can see re-reading this issue that we have left a fair bit of the discussion in the associated PR

https://github.com/ACCESS-NRI/schema/pull/5

If you've not read it I highly recommend doing so, then at the very least you can remind me what I thought then.

> What does the next level (your `model`) describe?

It's a perfectly valid question.

**Comment by dougiesquire** [comment]
> I can see re-reading this issue that we have left a fair bit of the discussion in the associated PR

Yeah I read this, but was still left unsure how other schema fit into the structure you arrived at. As a concrete example, where should the existing `experiment_asset.json` and `file_asset.json` schema live?

**Comment by aidanheerdegen** [comment]
> Yeah I read this, but was still left unsure how other schema fit into the structure you arrived at. As a concrete example, where should the existing `experiment_asset.json` and `file_asset.json` schema live?

Dunno. Whaddyareckon?

**Comment by CodeGat** [comment]
Yeah I hadn't added the other schema to the structure because I didn't know where they'd go yet - needed a bit of discussion.

**Comment by dougiesquire** [comment]
> Dunno. Whaddyareckon?

Could the second level try to clarify what the schema are for, e.g.:

```bash
au.org.access-nri/
├── model_reproducibility/
│   └── access-om2/
│       └── checksums/
│           ├── 1-0-0.json
│           └── CHANGELOG
└── model_output/
    ├── experiment_asset/
    │   ├── 1-0-0.json
    │   └── CHANGELOG
    └── file_asset/
        ├── 1-0-0.json
        └── CHANGELOG
bash

**Comment by aidanheerdegen** [comment]
That is closer to what I originally proposed and @CodeGat suggested we flip

https://github.com/ACCESS-NRI/schema/pull/5#issuecomment-1947422081

which convinced me.

This is a perennial problem with cataloguing anything, which is why, for our sins, we have the field of ontology.

We [currently have](https://tree.nathanfriend.io/?s=(%27options!(%27fancy!true~fullPath!false~trailingSlash!true~rootDot!false)~6(%276%27au.org.7nri5model5*7om23experiment3*reproducibility4checksums91-0-081-1-18CHANGELOG4performance9etc...%27)~version!%271%27)*%20%2035**43**5%5Cn*6source!7access-8.json4*9%2F4*%019876543*)

```
au.org.access-nri/
└── model/
    └── access-om2/
        └── experiment/
            └── reproducibility/
                ├── checksums/
                │   ├── 1-0-0.json
                │   ├── 1-1-1.json
                │   └── CHANGELOG
                └── performance/
                    └── etc...
```
 
Your suggestion [could be accomodated within that structure](https://tree.nathanfriend.io/?s=(%27options!(%27fancy!true~fullPath!false~trailingSlash!true~rootDot!false)~B(%27B%27au.org.Fnri5model5*Fom273*reproducibility39checksumsJI91-1-169839performanceJ*etc...5*output743file4%27)~version!%271%27)*%20%203594_asset3I85%5Cn*6.json3*73experiment8CHANGELOG9**Bsource!Faccess-I*1-0-06J%2F39%01JIFB9876543*)
```
au.org.access-nri/
└── model/
    ├── access-om2/
    │   └── experiment/
    │       └── reproducibility/
    │           ├── checksums/
    │           │   ├── 1-0-0.json
    │           │   ├── 1-1-1.json
    │           │   └── CHANGELOG
    │           └── performance/
    │               └── etc...
    └── output/
        ├── experiment_asset/
        │   ├── 1-0-0.json
        │   └── CHANGELOG
        └── file_asset/
            ├── 1-0-0.json
            └── CHANGELOG
```

Assuming that your schema are model independent. If they're not, then it might look more like this
```
au.org.access-nri/
└── model/
    └── access-om2/
        └── experiment/
            ├── reproducibility/
            │   ├── checksums/
            │   │   ├── 1-0-0.json
            │   │   ├── 1-1-1.json
            │   │   └── CHANGELOG
            │   └── performance/
            │       └── etc...
            └── output/
                ├── experiment_asset/
                │   ├── 1-0-0.json
                │   └── CHANGELOG
                └── file_asset/
                    ├── 1-0-0.json
                    └── CHANGELOG
```

Bear in mind I may have completely misunderstood.

**Comment by dougiesquire** [comment]
> Your suggestion [could be accomodated within that structure](https://tree.nathanfriend.io/?s=(%27options!(%27fancy!true~fullPath!false~trailingSlash!true~rootDot!false)~B(%27B%27au.org.Fnri5model5*Fom273*reproducibility39checksumsJI91-1-169839performanceJ*etc...5*output743file4%27)~version!%271%27)*%20%203594_asset3I85%5Cn*6.json3*73experiment8CHANGELOG9**Bsource!Faccess-I*1-0-06J%2F39%01JIFB9876543*)
> 
> ```
> au.org.access-nri/
> └── model/
>     ├── access-om2/
>     │   └── experiment/
>     │       └── reproducibility/
>     │           ├── checksums/
>     │           │   ├── 1-0-0.json
>     │           │   ├── 1-1-1.json
>     │           │   └── CHANGELOG
>     │           └── performance/
>     │               └── etc...
>     └── output/
>         ├── experiment_asset/
>         │   ├── 1-0-0.json
>         │   └── CHANGELOG
>         └── file_asset/
>             ├── 1-0-0.json
>             └── CHANGELOG
> ```

Sure I'm fine with this.

**Comment by aidanheerdegen** [comment]
> Sure I'm fine with this.

Please point out any problems. The further we get into this the more difficult it will be to rearrange, so if we need to change something now we definitely should.

We made a lot of these decisions while you were away, and would have valued your feedback at the time, but just had to plough on as we had some deadlines to miss.

**Comment by dougiesquire** [comment]
All good. I think my qualms with the structure are matters of opinion and probably aren't shared by the majority. What's on my mind is whether the current structure makes it easy to find schema. From a discoverability perspective, fewer levels of nesting and longer, more explicit, subdirectory names might help? It's not clear to me what the second level (`model`) describes, but that's probably because there's only one directory there at the moment. When there're others, things will probably make more sense. 

I'm happy with what you have, and I think you guys are best-placed to make the call since you have the best idea of what other schema may be added in the future.

**Comment by aidanheerdegen** [comment]
> I'm happy with what you have, and I think you guys are best-placed to make the call since you have the best idea of what other schema may be added in the future.

Well I don't think we did a lot of deep thinking TBH, and while too many voices can be counterproductive I'd like for there to be some more perspectives if possible. If you know anyone else who has experience/opinions about this please do ping them.

**Comment by aidanheerdegen** [comment]
Given his experience with JSON schema and validation with [axiom](https://axiom.readthedocs.io/en/latest/), we should probably ping @bschroeter in on this conversation

https://github.com/AusClimateService/axiom/blob/dev/specifications/mrd-0.2.0.json

**Comment by dougiesquire** [comment]
There are a few changes I'd like to make to the `*_asset.json` schema (#10, #11). But I think it's important to get these schema aligned with the others in the repo in terms of directory structure and versioning. Are we okay for me to slot in like this: https://github.com/ACCESS-NRI/schema/issues/4#issuecomment-1972489675.

Note, I may also change the names from `experiment_asset`/`file_asset` to `experiment_metadata`/`file_metadata`. Other suggestions are welcome.

**Comment by aidanheerdegen** [comment]
> Are we okay for me to slot in like this: [#4 (comment)](https://github.com/ACCESS-NRI/schema/issues/4#issuecomment-1972489675).

Absolutely. Up to you what you want to name it, but we'll need related PRs in `payu` and the intake catalogue.

**Comment by dougiesquire** [comment]
> but we'll need related PRs in payu and the intake catalogue.

Yeah, old versions of the intake catalogue will still work, since `access-nri-intake` [uses specific commits of the schema](https://github.com/ACCESS-NRI/access-nri-intake-catalog/blob/dfbef2ee2b771819ce4bacc7f165ecf9afab118d/src/access_nri_intake/source/__init__.py#L20-L21), but I guess this change will break old versions of Payu [which uses `main`](https://github.com/payu-org/payu/blob/421431b52c24dd57fa0ad023d46b739667133af7/payu/metadata.py#L39). Is it worth also keeping the `experiment_asset.json` in the base directory for a while (i.e. have two copies of this schema in the repo: one in `model/output/experiment_metadata` and one in the base directory)?
